// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basic-meta.proto

package com_webank_ai_fate_api_core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// network endpoint
type Endpoint struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{0}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Endpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Endpoint) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type Endpoints struct {
	Endpoints            []*Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Endpoints) Reset()         { *m = Endpoints{} }
func (m *Endpoints) String() string { return proto.CompactTextString(m) }
func (*Endpoints) ProtoMessage()    {}
func (*Endpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{1}
}

func (m *Endpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoints.Unmarshal(m, b)
}
func (m *Endpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoints.Marshal(b, m, deterministic)
}
func (m *Endpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoints.Merge(m, src)
}
func (m *Endpoints) XXX_Size() int {
	return xxx_messageInfo_Endpoints.Size(m)
}
func (m *Endpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoints.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoints proto.InternalMessageInfo

func (m *Endpoints) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// general container for serialized data
type Data struct {
	IsNull               bool     `protobuf:"varint,1,opt,name=isNull,proto3" json:"isNull,omitempty"`
	HostLanguage         string   `protobuf:"bytes,2,opt,name=hostLanguage,proto3" json:"hostLanguage,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

func (m *Data) GetHostLanguage() string {
	if m != nil {
		return m.HostLanguage
	}
	return ""
}

func (m *Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// general container for data list
type RepeatedData struct {
	Datalist             []*Data  `protobuf:"bytes,1,rep,name=datalist,proto3" json:"datalist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepeatedData) Reset()         { *m = RepeatedData{} }
func (m *RepeatedData) String() string { return proto.CompactTextString(m) }
func (*RepeatedData) ProtoMessage()    {}
func (*RepeatedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{3}
}

func (m *RepeatedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedData.Unmarshal(m, b)
}
func (m *RepeatedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedData.Marshal(b, m, deterministic)
}
func (m *RepeatedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedData.Merge(m, src)
}
func (m *RepeatedData) XXX_Size() int {
	return xxx_messageInfo_RepeatedData.Size(m)
}
func (m *RepeatedData) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedData.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedData proto.InternalMessageInfo

func (m *RepeatedData) GetDatalist() []*Data {
	if m != nil {
		return m.Datalist
	}
	return nil
}

// general message for a call request
type CallRequest struct {
	IsAsync              bool     `protobuf:"varint,1,opt,name=isAsync,proto3" json:"isAsync,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Command              string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Param                *Data    `protobuf:"bytes,4,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallRequest) Reset()         { *m = CallRequest{} }
func (m *CallRequest) String() string { return proto.CompactTextString(m) }
func (*CallRequest) ProtoMessage()    {}
func (*CallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{4}
}

func (m *CallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRequest.Unmarshal(m, b)
}
func (m *CallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRequest.Marshal(b, m, deterministic)
}
func (m *CallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRequest.Merge(m, src)
}
func (m *CallRequest) XXX_Size() int {
	return xxx_messageInfo_CallRequest.Size(m)
}
func (m *CallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallRequest proto.InternalMessageInfo

func (m *CallRequest) GetIsAsync() bool {
	if m != nil {
		return m.IsAsync
	}
	return false
}

func (m *CallRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CallRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CallRequest) GetParam() *Data {
	if m != nil {
		return m.Param
	}
	return nil
}

// general message for a call response
// todo: merge call response with Return Status
type CallResponse struct {
	ReturnStatus         *ReturnStatus `protobuf:"bytes,1,opt,name=returnStatus,proto3" json:"returnStatus,omitempty"`
	Result               *Data         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CallResponse) Reset()         { *m = CallResponse{} }
func (m *CallResponse) String() string { return proto.CompactTextString(m) }
func (*CallResponse) ProtoMessage()    {}
func (*CallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{5}
}

func (m *CallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResponse.Unmarshal(m, b)
}
func (m *CallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResponse.Marshal(b, m, deterministic)
}
func (m *CallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResponse.Merge(m, src)
}
func (m *CallResponse) XXX_Size() int {
	return xxx_messageInfo_CallResponse.Size(m)
}
func (m *CallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallResponse proto.InternalMessageInfo

func (m *CallResponse) GetReturnStatus() *ReturnStatus {
	if m != nil {
		return m.ReturnStatus
	}
	return nil
}

func (m *CallResponse) GetResult() *Data {
	if m != nil {
		return m.Result
	}
	return nil
}

type Job struct {
	JobId                string   `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{6}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Task struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	TaskId               int64    `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	TableId              int64    `protobuf:"varint,3,opt,name=tableId,proto3" json:"tableId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{7}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *Task) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Task) GetTableId() int64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

// reserved for driver async call result
type Result struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	ResultId             int64    `protobuf:"varint,2,opt,name=resultId,proto3" json:"resultId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{8}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Result) GetResultId() int64 {
	if m != nil {
		return m.ResultId
	}
	return 0
}

// generic return status
type ReturnStatus struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnStatus) Reset()         { *m = ReturnStatus{} }
func (m *ReturnStatus) String() string { return proto.CompactTextString(m) }
func (*ReturnStatus) ProtoMessage()    {}
func (*ReturnStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e566cac89a1c51ae, []int{9}
}

func (m *ReturnStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnStatus.Unmarshal(m, b)
}
func (m *ReturnStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnStatus.Marshal(b, m, deterministic)
}
func (m *ReturnStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnStatus.Merge(m, src)
}
func (m *ReturnStatus) XXX_Size() int {
	return xxx_messageInfo_ReturnStatus.Size(m)
}
func (m *ReturnStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnStatus proto.InternalMessageInfo

func (m *ReturnStatus) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReturnStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "com.webank.ai.fate.api.core.Endpoint")
	proto.RegisterType((*Endpoints)(nil), "com.webank.ai.fate.api.core.Endpoints")
	proto.RegisterType((*Data)(nil), "com.webank.ai.fate.api.core.Data")
	proto.RegisterType((*RepeatedData)(nil), "com.webank.ai.fate.api.core.RepeatedData")
	proto.RegisterType((*CallRequest)(nil), "com.webank.ai.fate.api.core.CallRequest")
	proto.RegisterType((*CallResponse)(nil), "com.webank.ai.fate.api.core.CallResponse")
	proto.RegisterType((*Job)(nil), "com.webank.ai.fate.api.core.Job")
	proto.RegisterType((*Task)(nil), "com.webank.ai.fate.api.core.Task")
	proto.RegisterType((*Result)(nil), "com.webank.ai.fate.api.core.Result")
	proto.RegisterType((*ReturnStatus)(nil), "com.webank.ai.fate.api.core.ReturnStatus")
}

func init() { proto.RegisterFile("basic-meta.proto", fileDescriptor_e566cac89a1c51ae) }

var fileDescriptor_e566cac89a1c51ae = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x8b, 0xd4, 0x30,
	0x14, 0xc7, 0xe9, 0x4e, 0x67, 0x9c, 0x79, 0x53, 0x44, 0x82, 0x48, 0xd1, 0x4b, 0x0d, 0x08, 0xe3,
	0xc1, 0x0a, 0x23, 0x22, 0x82, 0x1e, 0x64, 0xf5, 0x30, 0x83, 0x2b, 0x12, 0xbd, 0x79, 0x7a, 0x6d,
	0x9f, 0x6b, 0x66, 0xda, 0x26, 0x36, 0x29, 0xb2, 0xff, 0x87, 0x07, 0xff, 0x5c, 0x49, 0x9a, 0xce,
	0xee, 0x5e, 0xca, 0xde, 0xde, 0x37, 0x79, 0x2f, 0xef, 0xf3, 0x7e, 0x04, 0x1e, 0x14, 0x68, 0x64,
	0xf9, 0xa2, 0x21, 0x8b, 0xb9, 0xee, 0x94, 0x55, 0xec, 0x49, 0xa9, 0x9a, 0xfc, 0x0f, 0x15, 0xd8,
	0x1e, 0x73, 0x94, 0xf9, 0x4f, 0xb4, 0x94, 0xa3, 0x96, 0x79, 0xa9, 0x3a, 0xe2, 0x7b, 0x58, 0x7e,
	0x6a, 0x2b, 0xad, 0x64, 0x6b, 0xd9, 0x7d, 0x38, 0x93, 0x3a, 0x8d, 0xb2, 0x68, 0xb3, 0x12, 0x67,
	0x52, 0x33, 0x06, 0xb1, 0x56, 0x9d, 0x4d, 0xcf, 0xb2, 0x68, 0x33, 0x17, 0xde, 0x66, 0x8f, 0x61,
	0xf9, 0x4b, 0x19, 0xdb, 0x62, 0x43, 0xe9, 0xcc, 0x7b, 0x9e, 0x34, 0xff, 0x0a, 0xab, 0xf1, 0x2d,
	0xc3, 0xce, 0x61, 0x45, 0xa3, 0x48, 0xa3, 0x6c, 0xb6, 0x59, 0x6f, 0x9f, 0xe5, 0x13, 0x24, 0xf9,
	0x18, 0x2a, 0xae, 0xe3, 0xf8, 0x01, 0xe2, 0x8f, 0x68, 0x91, 0x3d, 0x82, 0x85, 0x34, 0x5f, 0xfa,
	0xba, 0xf6, 0x74, 0x4b, 0x11, 0x14, 0xe3, 0x90, 0xb8, 0xec, 0x9f, 0xb1, 0xbd, 0xec, 0xf1, 0x92,
	0x3c, 0xe9, 0x4a, 0xdc, 0x3a, 0x73, 0x55, 0xd8, 0x2b, 0x3d, 0xd2, 0x7a, 0xdb, 0x9d, 0x55, 0x68,
	0x31, 0x8d, 0xb3, 0x68, 0x93, 0x08, 0x6f, 0xf3, 0x0b, 0x48, 0x04, 0x69, 0x42, 0x4b, 0x95, 0xcf,
	0xf9, 0x1e, 0x96, 0xee, 0xbc, 0x96, 0xc6, 0x06, 0xfe, 0xa7, 0x93, 0xfc, 0x2e, 0x48, 0x9c, 0x42,
	0xf8, 0xdf, 0x08, 0xd6, 0xe7, 0x58, 0xd7, 0x82, 0x7e, 0xf7, 0x64, 0x2c, 0x4b, 0xe1, 0x9e, 0x34,
	0x1f, 0xcc, 0x55, 0x5b, 0x86, 0x1a, 0x46, 0xe9, 0x6e, 0xac, 0x6c, 0x48, 0xf5, 0x43, 0xa7, 0x67,
	0x62, 0x94, 0xee, 0xa6, 0x54, 0x4d, 0x83, 0x6d, 0x15, 0xe8, 0x47, 0xc9, 0xde, 0xc0, 0x5c, 0x63,
	0x87, 0x8d, 0xaf, 0xe0, 0x4e, 0x64, 0x83, 0x3f, 0xff, 0x17, 0x41, 0x32, 0x60, 0x19, 0xad, 0x5a,
	0x43, 0xec, 0x02, 0x92, 0x8e, 0x6c, 0xdf, 0xb5, 0xdf, 0x2c, 0xda, 0xde, 0x78, 0xb8, 0xf5, 0xf6,
	0xf9, 0xe4, 0x83, 0xe2, 0x46, 0x80, 0xb8, 0x15, 0xce, 0xde, 0xc2, 0xa2, 0x23, 0xd3, 0xd7, 0x43,
	0x2d, 0x77, 0x22, 0x0b, 0x01, 0xfc, 0x25, 0xcc, 0xf6, 0xaa, 0x60, 0x0f, 0x61, 0x7e, 0x50, 0xc5,
	0xae, 0x0a, 0x8b, 0x38, 0x08, 0x37, 0x31, 0xbf, 0x73, 0xc3, 0x84, 0xbd, 0xcd, 0x6b, 0x88, 0xbf,
	0xa3, 0x39, 0xb2, 0x2d, 0xcc, 0x0e, 0xaa, 0x08, 0xe4, 0xd9, 0x64, 0xc2, 0xbd, 0x2a, 0x84, 0x73,
	0x76, 0x1b, 0x65, 0xd1, 0x1c, 0x77, 0x55, 0xe8, 0x79, 0x50, 0x7e, 0x18, 0x58, 0xd4, 0xb4, 0x1b,
	0x5a, 0xee, 0x86, 0x31, 0x48, 0xfe, 0x03, 0x16, 0xc2, 0x83, 0xb2, 0xd7, 0x10, 0x3b, 0xef, 0x90,
	0x70, 0xba, 0x42, 0x07, 0x28, 0xbc, 0xbb, 0xfb, 0x3a, 0x43, 0xa5, 0xa7, 0xa4, 0x27, 0xcd, 0xdf,
	0xb9, 0xe5, 0xbb, 0xd1, 0x46, 0x06, 0x71, 0xa9, 0x2a, 0xf2, 0x29, 0xe6, 0xc2, 0xdb, 0x0e, 0xad,
	0x21, 0x63, 0xae, 0xf7, 0x7c, 0x94, 0xc5, 0xc2, 0x7f, 0xf4, 0x57, 0xff, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x1b, 0x75, 0xc5, 0xf4, 0xfc, 0x03, 0x00, 0x00,
}
