// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_service.proto

package com_webank_ai_fate_api_mlmodel_manager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Party struct {
	PartyId              []string `protobuf:"bytes,1,rep,name=partyId,proto3" json:"partyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Party) Reset()         { *m = Party{} }
func (m *Party) String() string { return proto.CompactTextString(m) }
func (*Party) ProtoMessage()    {}
func (*Party) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{0}
}

func (m *Party) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Party.Unmarshal(m, b)
}
func (m *Party) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Party.Marshal(b, m, deterministic)
}
func (m *Party) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Party.Merge(m, src)
}
func (m *Party) XXX_Size() int {
	return xxx_messageInfo_Party.Size(m)
}
func (m *Party) XXX_DiscardUnknown() {
	xxx_messageInfo_Party.DiscardUnknown(m)
}

var xxx_messageInfo_Party proto.InternalMessageInfo

func (m *Party) GetPartyId() []string {
	if m != nil {
		return m.PartyId
	}
	return nil
}

type LocalInfo struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	PartyId              string   `protobuf:"bytes,2,opt,name=partyId,proto3" json:"partyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalInfo) Reset()         { *m = LocalInfo{} }
func (m *LocalInfo) String() string { return proto.CompactTextString(m) }
func (*LocalInfo) ProtoMessage()    {}
func (*LocalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{1}
}

func (m *LocalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalInfo.Unmarshal(m, b)
}
func (m *LocalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalInfo.Marshal(b, m, deterministic)
}
func (m *LocalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalInfo.Merge(m, src)
}
func (m *LocalInfo) XXX_Size() int {
	return xxx_messageInfo_LocalInfo.Size(m)
}
func (m *LocalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LocalInfo proto.InternalMessageInfo

func (m *LocalInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *LocalInfo) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

type ModelInfo struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelInfo) Reset()         { *m = ModelInfo{} }
func (m *ModelInfo) String() string { return proto.CompactTextString(m) }
func (*ModelInfo) ProtoMessage()    {}
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{2}
}

func (m *ModelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelInfo.Unmarshal(m, b)
}
func (m *ModelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelInfo.Marshal(b, m, deterministic)
}
func (m *ModelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelInfo.Merge(m, src)
}
func (m *ModelInfo) XXX_Size() int {
	return xxx_messageInfo_ModelInfo.Size(m)
}
func (m *ModelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModelInfo proto.InternalMessageInfo

func (m *ModelInfo) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ModelInfo) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type RoleModelInfo struct {
	RoleModelInfo        map[string]*ModelInfo `protobuf:"bytes,1,rep,name=roleModelInfo,proto3" json:"roleModelInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RoleModelInfo) Reset()         { *m = RoleModelInfo{} }
func (m *RoleModelInfo) String() string { return proto.CompactTextString(m) }
func (*RoleModelInfo) ProtoMessage()    {}
func (*RoleModelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{3}
}

func (m *RoleModelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleModelInfo.Unmarshal(m, b)
}
func (m *RoleModelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleModelInfo.Marshal(b, m, deterministic)
}
func (m *RoleModelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleModelInfo.Merge(m, src)
}
func (m *RoleModelInfo) XXX_Size() int {
	return xxx_messageInfo_RoleModelInfo.Size(m)
}
func (m *RoleModelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleModelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleModelInfo proto.InternalMessageInfo

func (m *RoleModelInfo) GetRoleModelInfo() map[string]*ModelInfo {
	if m != nil {
		return m.RoleModelInfo
	}
	return nil
}

type UnloadRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadRequest) Reset()         { *m = UnloadRequest{} }
func (m *UnloadRequest) String() string { return proto.CompactTextString(m) }
func (*UnloadRequest) ProtoMessage()    {}
func (*UnloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{4}
}

func (m *UnloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadRequest.Unmarshal(m, b)
}
func (m *UnloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadRequest.Marshal(b, m, deterministic)
}
func (m *UnloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadRequest.Merge(m, src)
}
func (m *UnloadRequest) XXX_Size() int {
	return xxx_messageInfo_UnloadRequest.Size(m)
}
func (m *UnloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadRequest proto.InternalMessageInfo

func (m *UnloadRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *UnloadRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type UnloadResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadResponse) Reset()         { *m = UnloadResponse{} }
func (m *UnloadResponse) String() string { return proto.CompactTextString(m) }
func (*UnloadResponse) ProtoMessage()    {}
func (*UnloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{5}
}

func (m *UnloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadResponse.Unmarshal(m, b)
}
func (m *UnloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadResponse.Marshal(b, m, deterministic)
}
func (m *UnloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadResponse.Merge(m, src)
}
func (m *UnloadResponse) XXX_Size() int {
	return xxx_messageInfo_UnloadResponse.Size(m)
}
func (m *UnloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadResponse proto.InternalMessageInfo

func (m *UnloadResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UnloadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UnbindRequest struct {
	ServiceIds           []string `protobuf:"bytes,1,rep,name=serviceIds,proto3" json:"serviceIds,omitempty"`
	TableName            string   `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindRequest) Reset()         { *m = UnbindRequest{} }
func (m *UnbindRequest) String() string { return proto.CompactTextString(m) }
func (*UnbindRequest) ProtoMessage()    {}
func (*UnbindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{6}
}

func (m *UnbindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindRequest.Unmarshal(m, b)
}
func (m *UnbindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindRequest.Marshal(b, m, deterministic)
}
func (m *UnbindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindRequest.Merge(m, src)
}
func (m *UnbindRequest) XXX_Size() int {
	return xxx_messageInfo_UnbindRequest.Size(m)
}
func (m *UnbindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindRequest proto.InternalMessageInfo

func (m *UnbindRequest) GetServiceIds() []string {
	if m != nil {
		return m.ServiceIds
	}
	return nil
}

func (m *UnbindRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *UnbindRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type UnbindResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindResponse) Reset()         { *m = UnbindResponse{} }
func (m *UnbindResponse) String() string { return proto.CompactTextString(m) }
func (*UnbindResponse) ProtoMessage()    {}
func (*UnbindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{7}
}

func (m *UnbindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindResponse.Unmarshal(m, b)
}
func (m *UnbindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindResponse.Marshal(b, m, deterministic)
}
func (m *UnbindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindResponse.Merge(m, src)
}
func (m *UnbindResponse) XXX_Size() int {
	return xxx_messageInfo_UnbindResponse.Size(m)
}
func (m *UnbindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindResponse proto.InternalMessageInfo

func (m *UnbindResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UnbindResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryModelRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	TableName            string   `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	BeginIndex           int32    `protobuf:"varint,4,opt,name=beginIndex,proto3" json:"beginIndex,omitempty"`
	EndIndex             int32    `protobuf:"varint,5,opt,name=endIndex,proto3" json:"endIndex,omitempty"`
	QueryType            int32    `protobuf:"varint,6,opt,name=queryType,proto3" json:"queryType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryModelRequest) Reset()         { *m = QueryModelRequest{} }
func (m *QueryModelRequest) String() string { return proto.CompactTextString(m) }
func (*QueryModelRequest) ProtoMessage()    {}
func (*QueryModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{8}
}

func (m *QueryModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryModelRequest.Unmarshal(m, b)
}
func (m *QueryModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryModelRequest.Marshal(b, m, deterministic)
}
func (m *QueryModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModelRequest.Merge(m, src)
}
func (m *QueryModelRequest) XXX_Size() int {
	return xxx_messageInfo_QueryModelRequest.Size(m)
}
func (m *QueryModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModelRequest proto.InternalMessageInfo

func (m *QueryModelRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *QueryModelRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *QueryModelRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *QueryModelRequest) GetBeginIndex() int32 {
	if m != nil {
		return m.BeginIndex
	}
	return 0
}

func (m *QueryModelRequest) GetEndIndex() int32 {
	if m != nil {
		return m.EndIndex
	}
	return 0
}

func (m *QueryModelRequest) GetQueryType() int32 {
	if m != nil {
		return m.QueryType
	}
	return 0
}

type ModelBindInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelBindInfo) Reset()         { *m = ModelBindInfo{} }
func (m *ModelBindInfo) String() string { return proto.CompactTextString(m) }
func (*ModelBindInfo) ProtoMessage()    {}
func (*ModelBindInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{9}
}

func (m *ModelBindInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelBindInfo.Unmarshal(m, b)
}
func (m *ModelBindInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelBindInfo.Marshal(b, m, deterministic)
}
func (m *ModelBindInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelBindInfo.Merge(m, src)
}
func (m *ModelBindInfo) XXX_Size() int {
	return xxx_messageInfo_ModelBindInfo.Size(m)
}
func (m *ModelBindInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelBindInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModelBindInfo proto.InternalMessageInfo

type ModelProcessorExt struct {
	DslParser            string   `protobuf:"bytes,1,opt,name=dslParser,proto3" json:"dslParser,omitempty"`
	ParamsMap            string   `protobuf:"bytes,2,opt,name=paramsMap,proto3" json:"paramsMap,omitempty"`
	PipelineNodes        string   `protobuf:"bytes,3,opt,name=pipelineNodes,proto3" json:"pipelineNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelProcessorExt) Reset()         { *m = ModelProcessorExt{} }
func (m *ModelProcessorExt) String() string { return proto.CompactTextString(m) }
func (*ModelProcessorExt) ProtoMessage()    {}
func (*ModelProcessorExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{10}
}

func (m *ModelProcessorExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelProcessorExt.Unmarshal(m, b)
}
func (m *ModelProcessorExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelProcessorExt.Marshal(b, m, deterministic)
}
func (m *ModelProcessorExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelProcessorExt.Merge(m, src)
}
func (m *ModelProcessorExt) XXX_Size() int {
	return xxx_messageInfo_ModelProcessorExt.Size(m)
}
func (m *ModelProcessorExt) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelProcessorExt.DiscardUnknown(m)
}

var xxx_messageInfo_ModelProcessorExt proto.InternalMessageInfo

func (m *ModelProcessorExt) GetDslParser() string {
	if m != nil {
		return m.DslParser
	}
	return ""
}

func (m *ModelProcessorExt) GetParamsMap() string {
	if m != nil {
		return m.ParamsMap
	}
	return ""
}

func (m *ModelProcessorExt) GetPipelineNodes() string {
	if m != nil {
		return m.PipelineNodes
	}
	return ""
}

type ModelInfoEx struct {
	TableName  string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Namespace  string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceIds []string `protobuf:"bytes,3,rep,name=serviceIds,proto3" json:"serviceIds,omitempty"`
	Content    string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Index      int32    `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	//lx-todo
	ModelProcessorExt    *ModelProcessorExt `protobuf:"bytes,6,opt,name=modelProcessorExt,proto3" json:"modelProcessorExt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ModelInfoEx) Reset()         { *m = ModelInfoEx{} }
func (m *ModelInfoEx) String() string { return proto.CompactTextString(m) }
func (*ModelInfoEx) ProtoMessage()    {}
func (*ModelInfoEx) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{11}
}

func (m *ModelInfoEx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelInfoEx.Unmarshal(m, b)
}
func (m *ModelInfoEx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelInfoEx.Marshal(b, m, deterministic)
}
func (m *ModelInfoEx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelInfoEx.Merge(m, src)
}
func (m *ModelInfoEx) XXX_Size() int {
	return xxx_messageInfo_ModelInfoEx.Size(m)
}
func (m *ModelInfoEx) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelInfoEx.DiscardUnknown(m)
}

var xxx_messageInfo_ModelInfoEx proto.InternalMessageInfo

func (m *ModelInfoEx) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ModelInfoEx) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ModelInfoEx) GetServiceIds() []string {
	if m != nil {
		return m.ServiceIds
	}
	return nil
}

func (m *ModelInfoEx) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ModelInfoEx) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ModelInfoEx) GetModelProcessorExt() *ModelProcessorExt {
	if m != nil {
		return m.ModelProcessorExt
	}
	return nil
}

type QueryModelResponse struct {
	Retcode              int32          `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ModelInfos           []*ModelInfoEx `protobuf:"bytes,3,rep,name=modelInfos,proto3" json:"modelInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryModelResponse) Reset()         { *m = QueryModelResponse{} }
func (m *QueryModelResponse) String() string { return proto.CompactTextString(m) }
func (*QueryModelResponse) ProtoMessage()    {}
func (*QueryModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{12}
}

func (m *QueryModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryModelResponse.Unmarshal(m, b)
}
func (m *QueryModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryModelResponse.Marshal(b, m, deterministic)
}
func (m *QueryModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryModelResponse.Merge(m, src)
}
func (m *QueryModelResponse) XXX_Size() int {
	return xxx_messageInfo_QueryModelResponse.Size(m)
}
func (m *QueryModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryModelResponse proto.InternalMessageInfo

func (m *QueryModelResponse) GetRetcode() int32 {
	if m != nil {
		return m.Retcode
	}
	return 0
}

func (m *QueryModelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryModelResponse) GetModelInfos() []*ModelInfoEx {
	if m != nil {
		return m.ModelInfos
	}
	return nil
}

type PublishRequest struct {
	Local                *LocalInfo                `protobuf:"bytes,1,opt,name=local,proto3" json:"local,omitempty"`
	Role                 map[string]*Party         `protobuf:"bytes,2,rep,name=role,proto3" json:"role,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Model                map[string]*RoleModelInfo `protobuf:"bytes,3,rep,name=model,proto3" json:"model,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ServiceId            string                    `protobuf:"bytes,4,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	TableName            string                    `protobuf:"bytes,5,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Namespace            string                    `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LoadType             string                    `protobuf:"bytes,7,opt,name=loadType,proto3" json:"loadType,omitempty"`
	FilePath             string                    `protobuf:"bytes,8,opt,name=filePath,proto3" json:"filePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{13}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetLocal() *LocalInfo {
	if m != nil {
		return m.Local
	}
	return nil
}

func (m *PublishRequest) GetRole() map[string]*Party {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *PublishRequest) GetModel() map[string]*RoleModelInfo {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *PublishRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *PublishRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *PublishRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PublishRequest) GetLoadType() string {
	if m != nil {
		return m.LoadType
	}
	return ""
}

func (m *PublishRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type PublishResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{14}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *PublishResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PublishResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *PublishResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FetchModelRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SourceIp             string   `protobuf:"bytes,3,opt,name=sourceIp,proto3" json:"sourceIp,omitempty"`
	SourcePort           int32    `protobuf:"varint,4,opt,name=sourcePort,proto3" json:"sourcePort,omitempty"`
	TargetIp             string   `protobuf:"bytes,5,opt,name=targetIp,proto3" json:"targetIp,omitempty"`
	TargetPort           int32    `protobuf:"varint,6,opt,name=targetPort,proto3" json:"targetPort,omitempty"`
	ServiceId            string   `protobuf:"bytes,7,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchModelRequest) Reset()         { *m = FetchModelRequest{} }
func (m *FetchModelRequest) String() string { return proto.CompactTextString(m) }
func (*FetchModelRequest) ProtoMessage()    {}
func (*FetchModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{15}
}

func (m *FetchModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchModelRequest.Unmarshal(m, b)
}
func (m *FetchModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchModelRequest.Marshal(b, m, deterministic)
}
func (m *FetchModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchModelRequest.Merge(m, src)
}
func (m *FetchModelRequest) XXX_Size() int {
	return xxx_messageInfo_FetchModelRequest.Size(m)
}
func (m *FetchModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchModelRequest proto.InternalMessageInfo

func (m *FetchModelRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *FetchModelRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *FetchModelRequest) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *FetchModelRequest) GetSourcePort() int32 {
	if m != nil {
		return m.SourcePort
	}
	return 0
}

func (m *FetchModelRequest) GetTargetIp() string {
	if m != nil {
		return m.TargetIp
	}
	return ""
}

func (m *FetchModelRequest) GetTargetPort() int32 {
	if m != nil {
		return m.TargetPort
	}
	return 0
}

func (m *FetchModelRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type FetchModelResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchModelResponse) Reset()         { *m = FetchModelResponse{} }
func (m *FetchModelResponse) String() string { return proto.CompactTextString(m) }
func (*FetchModelResponse) ProtoMessage()    {}
func (*FetchModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{16}
}

func (m *FetchModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchModelResponse.Unmarshal(m, b)
}
func (m *FetchModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchModelResponse.Marshal(b, m, deterministic)
}
func (m *FetchModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchModelResponse.Merge(m, src)
}
func (m *FetchModelResponse) XXX_Size() int {
	return xxx_messageInfo_FetchModelResponse.Size(m)
}
func (m *FetchModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchModelResponse proto.InternalMessageInfo

func (m *FetchModelResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *FetchModelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ModelTransferRequest struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceId            string   `protobuf:"bytes,3,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelTransferRequest) Reset()         { *m = ModelTransferRequest{} }
func (m *ModelTransferRequest) String() string { return proto.CompactTextString(m) }
func (*ModelTransferRequest) ProtoMessage()    {}
func (*ModelTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{17}
}

func (m *ModelTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelTransferRequest.Unmarshal(m, b)
}
func (m *ModelTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelTransferRequest.Marshal(b, m, deterministic)
}
func (m *ModelTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelTransferRequest.Merge(m, src)
}
func (m *ModelTransferRequest) XXX_Size() int {
	return xxx_messageInfo_ModelTransferRequest.Size(m)
}
func (m *ModelTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModelTransferRequest proto.InternalMessageInfo

func (m *ModelTransferRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ModelTransferRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ModelTransferRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type ModelTransferResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ModelData            []byte   `protobuf:"bytes,3,opt,name=modelData,proto3" json:"modelData,omitempty"`
	CacheData            []byte   `protobuf:"bytes,4,opt,name=cacheData,proto3" json:"cacheData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelTransferResponse) Reset()         { *m = ModelTransferResponse{} }
func (m *ModelTransferResponse) String() string { return proto.CompactTextString(m) }
func (*ModelTransferResponse) ProtoMessage()    {}
func (*ModelTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ac95aa9096eaec, []int{18}
}

func (m *ModelTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelTransferResponse.Unmarshal(m, b)
}
func (m *ModelTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelTransferResponse.Marshal(b, m, deterministic)
}
func (m *ModelTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelTransferResponse.Merge(m, src)
}
func (m *ModelTransferResponse) XXX_Size() int {
	return xxx_messageInfo_ModelTransferResponse.Size(m)
}
func (m *ModelTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModelTransferResponse proto.InternalMessageInfo

func (m *ModelTransferResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ModelTransferResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ModelTransferResponse) GetModelData() []byte {
	if m != nil {
		return m.ModelData
	}
	return nil
}

func (m *ModelTransferResponse) GetCacheData() []byte {
	if m != nil {
		return m.CacheData
	}
	return nil
}

func init() {
	proto.RegisterType((*Party)(nil), "com.webank.ai.fate.api.mlmodel.manager.Party")
	proto.RegisterType((*LocalInfo)(nil), "com.webank.ai.fate.api.mlmodel.manager.LocalInfo")
	proto.RegisterType((*ModelInfo)(nil), "com.webank.ai.fate.api.mlmodel.manager.ModelInfo")
	proto.RegisterType((*RoleModelInfo)(nil), "com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo")
	proto.RegisterMapType((map[string]*ModelInfo)(nil), "com.webank.ai.fate.api.mlmodel.manager.RoleModelInfo.RoleModelInfoEntry")
	proto.RegisterType((*UnloadRequest)(nil), "com.webank.ai.fate.api.mlmodel.manager.UnloadRequest")
	proto.RegisterType((*UnloadResponse)(nil), "com.webank.ai.fate.api.mlmodel.manager.UnloadResponse")
	proto.RegisterType((*UnbindRequest)(nil), "com.webank.ai.fate.api.mlmodel.manager.UnbindRequest")
	proto.RegisterType((*UnbindResponse)(nil), "com.webank.ai.fate.api.mlmodel.manager.UnbindResponse")
	proto.RegisterType((*QueryModelRequest)(nil), "com.webank.ai.fate.api.mlmodel.manager.QueryModelRequest")
	proto.RegisterType((*ModelBindInfo)(nil), "com.webank.ai.fate.api.mlmodel.manager.ModelBindInfo")
	proto.RegisterType((*ModelProcessorExt)(nil), "com.webank.ai.fate.api.mlmodel.manager.ModelProcessorExt")
	proto.RegisterType((*ModelInfoEx)(nil), "com.webank.ai.fate.api.mlmodel.manager.ModelInfoEx")
	proto.RegisterType((*QueryModelResponse)(nil), "com.webank.ai.fate.api.mlmodel.manager.QueryModelResponse")
	proto.RegisterType((*PublishRequest)(nil), "com.webank.ai.fate.api.mlmodel.manager.PublishRequest")
	proto.RegisterMapType((map[string]*RoleModelInfo)(nil), "com.webank.ai.fate.api.mlmodel.manager.PublishRequest.ModelEntry")
	proto.RegisterMapType((map[string]*Party)(nil), "com.webank.ai.fate.api.mlmodel.manager.PublishRequest.RoleEntry")
	proto.RegisterType((*PublishResponse)(nil), "com.webank.ai.fate.api.mlmodel.manager.PublishResponse")
	proto.RegisterType((*FetchModelRequest)(nil), "com.webank.ai.fate.api.mlmodel.manager.FetchModelRequest")
	proto.RegisterType((*FetchModelResponse)(nil), "com.webank.ai.fate.api.mlmodel.manager.FetchModelResponse")
	proto.RegisterType((*ModelTransferRequest)(nil), "com.webank.ai.fate.api.mlmodel.manager.ModelTransferRequest")
	proto.RegisterType((*ModelTransferResponse)(nil), "com.webank.ai.fate.api.mlmodel.manager.ModelTransferResponse")
}

func init() { proto.RegisterFile("model_service.proto", fileDescriptor_b8ac95aa9096eaec) }

var fileDescriptor_b8ac95aa9096eaec = []byte{
	// 1017 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x96, 0x93, 0xcd, 0x26, 0x39, 0x69, 0x5a, 0x32, 0x2d, 0x52, 0x64, 0x55, 0xa8, 0x58, 0x08,
	0xf5, 0x06, 0x4b, 0xa4, 0xa2, 0xd0, 0x0a, 0x24, 0xd8, 0x76, 0x59, 0x42, 0xdb, 0x25, 0xb8, 0x8b,
	0xb8, 0x44, 0x13, 0xfb, 0x24, 0x6b, 0xad, 0xed, 0xf1, 0xce, 0xd8, 0xed, 0xe6, 0x06, 0x21, 0xb8,
	0x85, 0x47, 0x80, 0xd7, 0xe1, 0x49, 0x78, 0x02, 0x78, 0x00, 0x34, 0x33, 0xfe, 0x4d, 0xc2, 0x2a,
	0x3f, 0xa8, 0x77, 0x73, 0xce, 0xf8, 0x9c, 0xf9, 0xce, 0xc9, 0x37, 0xdf, 0x99, 0xc0, 0xed, 0x90,
	0x79, 0x18, 0xfc, 0x20, 0x90, 0xbf, 0xf2, 0x5d, 0xb4, 0x63, 0xce, 0x12, 0x46, 0xde, 0x77, 0x59,
	0x68, 0xbf, 0xc6, 0x29, 0x8d, 0x2e, 0x6c, 0xea, 0xdb, 0x33, 0x9a, 0xa0, 0x4d, 0x63, 0xdf, 0x0e,
	0x03, 0xf5, 0xb5, 0x1d, 0xd2, 0x88, 0xce, 0x91, 0x5b, 0xef, 0x42, 0x6b, 0x42, 0x79, 0xb2, 0x20,
	0x43, 0x68, 0xc7, 0x72, 0x31, 0xf6, 0x86, 0xc6, 0xbd, 0xe6, 0xfd, 0xae, 0x93, 0x9b, 0xd6, 0x23,
	0xe8, 0x3e, 0x67, 0x2e, 0x0d, 0xc6, 0xd1, 0x8c, 0x11, 0x02, 0x07, 0x9c, 0x05, 0x38, 0x34, 0xee,
	0x19, 0xf7, 0xbb, 0x8e, 0x5a, 0x57, 0x43, 0x1b, 0xca, 0x5d, 0x84, 0x9e, 0x40, 0xf7, 0x85, 0x3c,
	0x4e, 0x85, 0xde, 0x85, 0x6e, 0x42, 0xa7, 0x01, 0x9e, 0xd2, 0x30, 0x8f, 0x2f, 0x1d, 0x72, 0x37,
	0xa2, 0x21, 0x8a, 0x98, 0xba, 0x98, 0xa5, 0x29, 0x1d, 0xd6, 0x3f, 0x06, 0xf4, 0x1d, 0x16, 0x60,
	0x99, 0x2d, 0x82, 0x3e, 0xaf, 0x3a, 0x14, 0xea, 0xde, 0xe8, 0x2b, 0x7b, 0xb3, 0xc2, 0xed, 0x5a,
	0xb6, 0xba, 0x75, 0x1c, 0x25, 0x7c, 0xe1, 0xd4, 0xd3, 0x9b, 0x02, 0xc8, 0xea, 0x47, 0xe4, 0x2d,
	0x68, 0x5e, 0xe0, 0x22, 0xab, 0x46, 0x2e, 0xc9, 0x09, 0xb4, 0x5e, 0xd1, 0x20, 0xd5, 0x35, 0xf4,
	0x46, 0x1f, 0x6e, 0x8a, 0xa7, 0x48, 0xec, 0xe8, 0xf8, 0xc7, 0x8d, 0x4f, 0x0c, 0xeb, 0x19, 0xf4,
	0xbf, 0x8b, 0x02, 0x46, 0x3d, 0x07, 0x2f, 0x53, 0x14, 0xc9, 0x5e, 0x3d, 0xfc, 0x1a, 0x6e, 0xe6,
	0xc9, 0x44, 0xcc, 0x22, 0x81, 0xe4, 0x1d, 0x00, 0x91, 0xd0, 0x24, 0x15, 0x4f, 0x98, 0xa7, 0xd3,
	0xb5, 0x9c, 0x8a, 0x47, 0xfe, 0xb0, 0x21, 0x0a, 0x41, 0xe7, 0x79, 0xb6, 0xdc, 0xb4, 0x2e, 0x24,
	0xb0, 0xa9, 0x1f, 0x15, 0xc0, 0x64, 0x2a, 0x4d, 0xc0, 0xb1, 0x27, 0x32, 0x06, 0x55, 0x3c, 0x75,
	0xe0, 0x8d, 0x6b, 0x81, 0x37, 0xd7, 0x02, 0xd7, 0x87, 0xed, 0x0d, 0xfc, 0x4f, 0x03, 0x06, 0xdf,
	0xa6, 0xc8, 0x17, 0xaa, 0xdf, 0x95, 0xb6, 0x16, 0x58, 0xf3, 0xb6, 0x16, 0x8e, 0x7d, 0xb0, 0x4b,
	0xa4, 0x53, 0x9c, 0xfb, 0xd1, 0x38, 0xf2, 0xf0, 0x6a, 0x78, 0xa0, 0x91, 0x96, 0x1e, 0x62, 0x42,
	0x07, 0x23, 0x4f, 0xef, 0xb6, 0xd4, 0x6e, 0x61, 0xcb, 0xcc, 0x97, 0x12, 0xea, 0xd9, 0x22, 0xc6,
	0xe1, 0xa1, 0xda, 0x2c, 0x1d, 0xd6, 0x2d, 0xe8, 0xab, 0x1a, 0x8e, 0x7c, 0xf9, 0xfd, 0x8c, 0x59,
	0x29, 0x0c, 0x94, 0x63, 0xc2, 0x99, 0x8b, 0x42, 0x30, 0x7e, 0x7c, 0xa5, 0x2a, 0xf3, 0x44, 0x30,
	0xa1, 0x5c, 0x20, 0xcf, 0x2b, 0x2b, 0x1c, 0x72, 0x37, 0xa6, 0x9c, 0x86, 0xe2, 0x05, 0x8d, 0xf3,
	0xca, 0x0a, 0x07, 0x79, 0x0f, 0xfa, 0xb1, 0x1f, 0x63, 0xe0, 0x47, 0x78, 0xca, 0x3c, 0x14, 0x59,
	0x75, 0x75, 0xa7, 0xf5, 0x73, 0x03, 0x7a, 0xe5, 0xad, 0xb8, 0xda, 0x87, 0xa2, 0x4b, 0x2c, 0x6a,
	0xae, 0xb0, 0x68, 0x08, 0x6d, 0x97, 0x45, 0x09, 0x46, 0x89, 0x6a, 0x65, 0xd7, 0xc9, 0x4d, 0x72,
	0x07, 0x5a, 0x7e, 0xa5, 0x89, 0xda, 0x20, 0x73, 0x18, 0x84, 0xcb, 0x2d, 0x51, 0x9d, 0xec, 0x8d,
	0x1e, 0x6d, 0x75, 0x31, 0xab, 0x09, 0x9c, 0xd5, 0x9c, 0xd6, 0xef, 0x06, 0x90, 0x2a, 0xad, 0x32,
	0x9e, 0x0e, 0xa1, 0xcd, 0x31, 0x71, 0x4b, 0x92, 0xe6, 0xe6, 0x7f, 0x33, 0x94, 0xbc, 0x04, 0x08,
	0xf3, 0x76, 0xea, 0x1e, 0xf4, 0x46, 0x0f, 0xb6, 0x56, 0x91, 0xe3, 0x2b, 0xa7, 0x92, 0xc6, 0xfa,
	0xfb, 0x00, 0x6e, 0x4e, 0xd2, 0x69, 0xe0, 0x8b, 0xf3, 0x9c, 0xf3, 0x27, 0xd0, 0x0a, 0xa4, 0xac,
	0x2b, 0x64, 0x5b, 0x08, 0x55, 0x31, 0x0b, 0x1c, 0x1d, 0x4f, 0xce, 0xb2, 0x91, 0xd0, 0x50, 0x50,
	0x3f, 0xdf, 0x34, 0x4f, 0x1d, 0x8e, 0x52, 0x60, 0x2d, 0xbc, 0x7a, 0xa8, 0x7c, 0x0f, 0x2d, 0xf5,
	0x7d, 0xd6, 0x81, 0x2f, 0x76, 0x4c, 0xab, 0x1a, 0xa2, 0xf3, 0xea, 0x7c, 0xf5, 0xbb, 0x7e, 0x70,
	0xed, 0x5d, 0x6f, 0x5d, 0xcb, 0xde, 0xc3, 0x65, 0xf6, 0x9a, 0xd0, 0x91, 0xf2, 0xaa, 0xae, 0x6b,
	0x5b, 0x6d, 0x16, 0xb6, 0xdc, 0x9b, 0xf9, 0x01, 0x4e, 0x68, 0x72, 0x3e, 0xec, 0xe8, 0xbd, 0xdc,
	0x36, 0x67, 0xd0, 0x2d, 0xaa, 0x5f, 0x33, 0x51, 0x9e, 0xd4, 0x27, 0xca, 0x07, 0x1b, 0x77, 0x42,
	0x0e, 0xe1, 0xca, 0x34, 0x31, 0x19, 0x40, 0xd9, 0x8e, 0x35, 0x07, 0x3d, 0xab, 0x1f, 0xf4, 0xd1,
	0x4e, 0xa3, 0xb4, 0x3a, 0xbe, 0x52, 0xb8, 0x55, 0xfc, 0x1c, 0xfb, 0x2a, 0xb7, 0xbc, 0xe1, 0xc8,
	0x39, 0xe3, 0x99, 0x0a, 0x69, 0x43, 0xbe, 0x47, 0x3c, 0x9a, 0x50, 0xf5, 0x43, 0xde, 0x70, 0xd4,
	0xda, 0xfa, 0xcb, 0x80, 0xc1, 0x97, 0x98, 0xb8, 0xe7, 0xcb, 0x1a, 0xbf, 0xb3, 0x2e, 0x99, 0xd0,
	0x11, 0x2c, 0xe5, 0x2e, 0x8e, 0xe3, 0xec, 0xf8, 0xc2, 0x56, 0x15, 0xa9, 0xf5, 0x84, 0xf1, 0x24,
	0x57, 0xf8, 0xd2, 0x23, 0x63, 0x13, 0xca, 0xe7, 0x98, 0x8c, 0xe3, 0x8c, 0x50, 0x85, 0x2d, 0x63,
	0xf5, 0x5a, 0xc5, 0x6a, 0x89, 0xaf, 0x78, 0xea, 0x5c, 0x6d, 0x2f, 0x71, 0xd5, 0x3a, 0x05, 0x52,
	0x2d, 0x73, 0xef, 0xd9, 0x18, 0xc3, 0x1d, 0x95, 0xea, 0x8c, 0xd3, 0x48, 0xcc, 0x90, 0xff, 0x1f,
	0x9d, 0xab, 0x55, 0xd0, 0x5c, 0xae, 0xe0, 0x37, 0x03, 0xde, 0x5e, 0x3a, 0x72, 0x6f, 0x9e, 0xdc,
	0x85, 0xae, 0xa2, 0xe7, 0x53, 0x49, 0x8b, 0xa6, 0xa2, 0x45, 0xe9, 0x90, 0xbb, 0x2e, 0x75, 0xcf,
	0xf1, 0x69, 0x49, 0x9a, 0xd2, 0x31, 0xfa, 0xa3, 0x03, 0x37, 0x14, 0x9e, 0x97, 0x1a, 0x22, 0xf9,
	0x11, 0x7a, 0xb1, 0x66, 0xf0, 0x73, 0x46, 0x3d, 0xf2, 0x70, 0x37, 0x15, 0x32, 0x3f, 0xde, 0x3a,
	0x2e, 0x6b, 0x43, 0x79, 0xbe, 0x1c, 0xf3, 0x6f, 0xfe, 0xfc, 0x9f, 0x0c, 0xe8, 0x67, 0x00, 0xbe,
	0x89, 0xe4, 0xcc, 0x7f, 0xf3, 0x10, 0x7e, 0x31, 0x00, 0x2e, 0x8b, 0xd1, 0x4a, 0x36, 0x9e, 0xdb,
	0x2b, 0xaf, 0x3c, 0xf3, 0xf1, 0x2e, 0xa1, 0x19, 0x8a, 0xd7, 0x70, 0x98, 0xaa, 0xc7, 0x33, 0xd9,
	0x58, 0x16, 0x6b, 0x2f, 0x77, 0xf3, 0xe1, 0xb6, 0x61, 0xd5, 0x83, 0xe5, 0xe3, 0x77, 0x9b, 0x83,
	0x2b, 0x2f, 0xf3, 0x6d, 0x0e, 0xae, 0xbd, 0xb1, 0x65, 0xdf, 0x67, 0x85, 0xbc, 0x6c, 0xde, 0xf7,
	0x15, 0xe5, 0xdd, 0xbc, 0xef, 0x6b, 0xd4, 0xec, 0x57, 0x03, 0xfa, 0x61, 0x55, 0x21, 0xc8, 0xa7,
	0x5b, 0xbd, 0x85, 0x96, 0xb4, 0xcc, 0xfc, 0x6c, 0xc7, 0x68, 0x0d, 0xe7, 0xe8, 0xf6, 0xd1, 0xa0,
	0xaa, 0x0f, 0x13, 0xf9, 0x5f, 0x7b, 0x7a, 0xa8, 0xfe, 0x72, 0x3f, 0xf8, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0x79, 0xf4, 0x70, 0x89, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModelServiceClient is the client API for ModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelServiceClient interface {
	PublishLoad(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	PublishBind(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	PublishOnline(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	QueryModel(ctx context.Context, in *QueryModelRequest, opts ...grpc.CallOption) (*QueryModelResponse, error)
	Unload(ctx context.Context, in *UnloadRequest, opts ...grpc.CallOption) (*UnloadResponse, error)
	Unbind(ctx context.Context, in *UnbindRequest, opts ...grpc.CallOption) (*UnbindResponse, error)
	FetchModel(ctx context.Context, in *FetchModelRequest, opts ...grpc.CallOption) (*FetchModelResponse, error)
	ModelTransfer(ctx context.Context, in *ModelTransferRequest, opts ...grpc.CallOption) (*ModelTransferResponse, error)
}

type modelServiceClient struct {
	cc *grpc.ClientConn
}

func NewModelServiceClient(cc *grpc.ClientConn) ModelServiceClient {
	return &modelServiceClient{cc}
}

func (c *modelServiceClient) PublishLoad(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/com.webank.ai.fate.api.mlmodel.manager.ModelService/publishLoad", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) PublishBind(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/com.webank.ai.fate.api.mlmodel.manager.ModelService/publishBind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) PublishOnline(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/com.webank.ai.fate.api.mlmodel.manager.ModelService/publishOnline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) QueryModel(ctx context.Context, in *QueryModelRequest, opts ...grpc.CallOption) (*QueryModelResponse, error) {
	out := new(QueryModelResponse)
	err := c.cc.Invoke(ctx, "/com.webank.ai.fate.api.mlmodel.manager.ModelService/queryModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) Unload(ctx context.Context, in *UnloadRequest, opts ...grpc.CallOption) (*UnloadResponse, error) {
	out := new(UnloadResponse)
	err := c.cc.Invoke(ctx, "/com.webank.ai.fate.api.mlmodel.manager.ModelService/unload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) Unbind(ctx context.Context, in *UnbindRequest, opts ...grpc.CallOption) (*UnbindResponse, error) {
	out := new(UnbindResponse)
	err := c.cc.Invoke(ctx, "/com.webank.ai.fate.api.mlmodel.manager.ModelService/unbind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) FetchModel(ctx context.Context, in *FetchModelRequest, opts ...grpc.CallOption) (*FetchModelResponse, error) {
	out := new(FetchModelResponse)
	err := c.cc.Invoke(ctx, "/com.webank.ai.fate.api.mlmodel.manager.ModelService/fetchModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ModelTransfer(ctx context.Context, in *ModelTransferRequest, opts ...grpc.CallOption) (*ModelTransferResponse, error) {
	out := new(ModelTransferResponse)
	err := c.cc.Invoke(ctx, "/com.webank.ai.fate.api.mlmodel.manager.ModelService/modelTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServiceServer is the server API for ModelService service.
type ModelServiceServer interface {
	PublishLoad(context.Context, *PublishRequest) (*PublishResponse, error)
	PublishBind(context.Context, *PublishRequest) (*PublishResponse, error)
	PublishOnline(context.Context, *PublishRequest) (*PublishResponse, error)
	QueryModel(context.Context, *QueryModelRequest) (*QueryModelResponse, error)
	Unload(context.Context, *UnloadRequest) (*UnloadResponse, error)
	Unbind(context.Context, *UnbindRequest) (*UnbindResponse, error)
	FetchModel(context.Context, *FetchModelRequest) (*FetchModelResponse, error)
	ModelTransfer(context.Context, *ModelTransferRequest) (*ModelTransferResponse, error)
}

// UnimplementedModelServiceServer can be embedded to have forward compatible implementations.
type UnimplementedModelServiceServer struct {
}

func (*UnimplementedModelServiceServer) PublishLoad(ctx context.Context, req *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishLoad not implemented")
}
func (*UnimplementedModelServiceServer) PublishBind(ctx context.Context, req *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishBind not implemented")
}
func (*UnimplementedModelServiceServer) PublishOnline(ctx context.Context, req *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishOnline not implemented")
}
func (*UnimplementedModelServiceServer) QueryModel(ctx context.Context, req *QueryModelRequest) (*QueryModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryModel not implemented")
}
func (*UnimplementedModelServiceServer) Unload(ctx context.Context, req *UnloadRequest) (*UnloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unload not implemented")
}
func (*UnimplementedModelServiceServer) Unbind(ctx context.Context, req *UnbindRequest) (*UnbindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unbind not implemented")
}
func (*UnimplementedModelServiceServer) FetchModel(ctx context.Context, req *FetchModelRequest) (*FetchModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchModel not implemented")
}
func (*UnimplementedModelServiceServer) ModelTransfer(ctx context.Context, req *ModelTransferRequest) (*ModelTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelTransfer not implemented")
}

func RegisterModelServiceServer(s *grpc.Server, srv ModelServiceServer) {
	s.RegisterService(&_ModelService_serviceDesc, srv)
}

func _ModelService_PublishLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).PublishLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.webank.ai.fate.api.mlmodel.manager.ModelService/PublishLoad",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).PublishLoad(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_PublishBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).PublishBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.webank.ai.fate.api.mlmodel.manager.ModelService/PublishBind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).PublishBind(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_PublishOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).PublishOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.webank.ai.fate.api.mlmodel.manager.ModelService/PublishOnline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).PublishOnline(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_QueryModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).QueryModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.webank.ai.fate.api.mlmodel.manager.ModelService/QueryModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).QueryModel(ctx, req.(*QueryModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_Unload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).Unload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.webank.ai.fate.api.mlmodel.manager.ModelService/Unload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).Unload(ctx, req.(*UnloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_Unbind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).Unbind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.webank.ai.fate.api.mlmodel.manager.ModelService/Unbind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).Unbind(ctx, req.(*UnbindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_FetchModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).FetchModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.webank.ai.fate.api.mlmodel.manager.ModelService/FetchModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).FetchModel(ctx, req.(*FetchModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ModelTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ModelTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.webank.ai.fate.api.mlmodel.manager.ModelService/ModelTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ModelTransfer(ctx, req.(*ModelTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.webank.ai.fate.api.mlmodel.manager.ModelService",
	HandlerType: (*ModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "publishLoad",
			Handler:    _ModelService_PublishLoad_Handler,
		},
		{
			MethodName: "publishBind",
			Handler:    _ModelService_PublishBind_Handler,
		},
		{
			MethodName: "publishOnline",
			Handler:    _ModelService_PublishOnline_Handler,
		},
		{
			MethodName: "queryModel",
			Handler:    _ModelService_QueryModel_Handler,
		},
		{
			MethodName: "unload",
			Handler:    _ModelService_Unload_Handler,
		},
		{
			MethodName: "unbind",
			Handler:    _ModelService_Unbind_Handler,
		},
		{
			MethodName: "fetchModel",
			Handler:    _ModelService_FetchModel_Handler,
		},
		{
			MethodName: "modelTransfer",
			Handler:    _ModelService_ModelTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model_service.proto",
}
